controller_manager:
  ros__parameters:
    update_rate: 50
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
  
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      


diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["base_left_wheel_joint"]
    right_wheel_names: ["base_right_wheel_joint"]
    wheel_separation: 0.45
    wheel_radius: 0.1
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    pose_covariance_diagonal: [0.001, 0.001, 0.010, 0.010, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.010, 0.010, 0.001, 0.01]
    enable_odom_tf: true
    publish_rate: 50.0
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
