<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_length" value="0.1"/>
    <xacro:property name="arm_base_width" value="0.1"/>
    <xacro:property name="arm_base_height" value="0.01"/>
    <xacro:property name="arm_length" value="0.3"/>
    <xacro:property name="arm_radius" value="0.02"/>

   
    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="arm_base"/>
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertial m="0.5" x="${arm_base_length}" y="${arm_base_width}" z="${arm_base_height}"
                                o_xyz="0 0 0" o_rpy="0 0 0"/>

    
    </link>

    <link name="forearm_link">
       <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}"/>
            </geometry>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
            <material name="forearm"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}"/>
            </geometry>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertial m="0.3" r="${arm_radius}" h="${arm_length}"
                                   o_xyz="0 0 ${arm_length/2}" o_rpy="0 0 0"/>

    </link>

    <link name="hand_link">
       <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}"/>
            </geometry>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
            <material name="hand"/>
        </visual>
         <collision>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_length}"/>
            </geometry>
            <origin xyz="0 0 ${arm_length/2}" rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertial m="0.3" r="${arm_radius}" h="${arm_length}"
                                   o_xyz="0 0 ${arm_length/2}" o_rpy="0 0 0"/>

    </link>



    <joint name="arm_base_to_forearm_joint" type="revolute">
        <parent link="arm_base_link"/>
        <child link="forearm_link"/>
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" velocity="100" lower="0" upper="${pi/2}"/>
        <dynamics friction="0.3" damping="0.3" />
    </joint>

   <joint name="forearm_to_hand_joint" type="revolute">
       <parent link="forearm_link"/>
       <child link="hand_link"/>
       <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
       <axis xyz="0 1 0"/>
       <limit effort="100" velocity="100" lower="0" upper="${pi/2}"/>
       <dynamics friction="0.3" damping="0.3" />
   </joint>


</robot>
