<?xml version="1.0"?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro"/>
    <xacro:include filename="mobile_base.xacro"/>
    <!-- <xacro:include filename="mobile_base_ros2_control.xacro"/> -->
    <!-- <xacro:include filename="camera.xacro"/> -->
    <xacro:include filename="lidar.xacro"/>

<!-- 
    <xacro:include filename="camera.xacro"/>
    <xacro:include filename="arm.xacro"/>
    
    <joint name = "arm_base_to_mobile_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="arm_base_link"/>
        <origin xyz="${base_length/3.0} 0 ${base_height}" rpy="0 0 0"/>
    </joint>

     -->


</robot>