<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_radius" value="0.1" />
    <xacro:property name="lidar_height" value="0.05" />

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}" />
            </geometry>
            <origin xyz="0 0 ${-lidar_height / 2.0}" rpy="0 0 0" />
            <material name="lidar" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}" />
            </geometry>
            <origin xyz="0 0 ${-lidar_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertial m="0.1" x="${lidar_radius * 2}" y="${lidar_radius * 2}" z="${lidar_height}"
                           o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_link" />
        <origin xyz="0 0 ${base_height + lidar_height}" rpy="0 0 0" />
    </joint>



</robot>