<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>

    <link name="base_footprint">
    </link>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
            <material name="body"/>
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
        </collision>

        <xacro:box_inertial m="5.0" x="${base_length}" y="${base_width}" z="${base_height}"
                                o_xyz="0 0 ${base_height/2.0}" o_rpy="0 0 0"/>
    </link>

   <link name = "caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius/2}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="caster_wheel"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${wheel_radius/2}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>

        <xacro:sphere_inertial m="0.5" r="${wheel_radius/2}" o_xyz="0 0 0" o_rpy="0 0 0"/>
   </link>

    <link name = "right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
            <material name="wheel"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>

        <xacro:cylinder_inertial m="1.0" r="${wheel_radius}" h="${wheel_length}" o_xyz="0 0 0" o_rpy="${pi/2.0} 0 0"/>
    </link>

    <link name = "left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
            <material name="wheel"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>

        <xacro:cylinder_inertial m="1.0" r="${wheel_radius}" h="${wheel_length}" o_xyz="0 0 0" o_rpy="${pi/2.0} 0 0"/>
    </link>


    <joint name = "base_footprint_base_link" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${-base_length/4.0} ${-(base_width/2.0 + wheel_length/2.0)} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length/4.0} ${(base_width/2.0 + wheel_length/2.0)} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="${base_length/-3.0} 0 ${wheel_radius/-2.0}" rpy="0 0 0"/>
    </joint>

</robot>